"""Clients and client entities (glossary). TASK-008 design §1."""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from sqlalchemy import FetchedValue
from sqlalchemy.orm import Mapped, mapped_column

from abacus.kernel.db import Base


class Client(Base):
    __tablename__ = "clients"

    id: Mapped[UUID] = mapped_column(primary_key=True)
    tenant_id: Mapped[UUID]
    name: Mapped[str]
    created_at: Mapped[datetime]
    # SPEC-025: generated by the database (`organisations.normalise` mirrors it).
    normalised_name: Mapped[str] = mapped_column(server_default=FetchedValue())


class ClientEntity(Base):
    __tablename__ = "client_entities"

    id: Mapped[UUID] = mapped_column(primary_key=True)
    tenant_id: Mapped[UUID]
    client_id: Mapped[UUID]
    name: Mapped[str]
    created_at: Mapped[datetime]
    normalised_name: Mapped[str] = mapped_column(server_default=FetchedValue())
