"""Public interface of the identity module; other modules import only this (ADR-008)."""

from abacus.modules.identity.authz import (
    MFA_RECENT,
    WALL_SAFE,
    Forbidden,
    Resource,
    UnknownAction,
    agent_may_hold,
    authorise,
    register_engagement_client,
    serving_request,
    visible,
)
from abacus.modules.identity.context import (
    Actor,
    AgentContext,
    AuthContext,
    NoActiveTenant,
    SystemContext,
    agent_context_for_run,
    system_context_for_run,
)
from abacus.modules.identity.repository import EngagementRole
from abacus.modules.identity.routes import router
from abacus.modules.identity.routing import (
    ACTION_KEY,
    SELF,
    AbacusRoute,
    AbacusRouter,
    current_context,
    current_signed_in,
    declared_action,
)
from abacus.modules.identity.service import (
    TeamMember,
    add_creator_as_partner,
    could,
    engagement_team,
    is_active_member,
)
from abacus.modules.identity.tokens import (
    InvalidToken,
    JwtVerifier,
    TokenVerifier,
    VerifiedIdentity,
    configure_verifier,
    reset_verifier,
    token_verifier,
)

__all__ = [
    "ACTION_KEY",
    "MFA_RECENT",
    "SELF",
    "WALL_SAFE",
    "AbacusRoute",
    "AbacusRouter",
    "Actor",
    "AgentContext",
    "AuthContext",
    "EngagementRole",
    "Forbidden",
    "InvalidToken",
    "JwtVerifier",
    "NoActiveTenant",
    "Resource",
    "SystemContext",
    "TeamMember",
    "TokenVerifier",
    "UnknownAction",
    "VerifiedIdentity",
    "add_creator_as_partner",
    "agent_context_for_run",
    "agent_may_hold",
    "authorise",
    "configure_verifier",
    "could",
    "current_context",
    "current_signed_in",
    "declared_action",
    "engagement_team",
    "is_active_member",
    "register_engagement_client",
    "reset_verifier",
    "router",
    "serving_request",
    "system_context_for_run",
    "token_verifier",
    "visible",
]
