// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateEngagementData, CreateEngagementErrors, CreateEngagementResponses, CreateRequestItemData, CreateRequestItemErrors, CreateRequestItemResponses, GetEngagementData, GetEngagementErrors, GetEngagementResponses, GetRetrievalData, GetRetrievalErrors, GetRetrievalResponses, ListEngagementsData, ListEngagementsErrors, ListEngagementsResponses, ListRequestItemsData, ListRequestItemsErrors, ListRequestItemsResponses, MeData, MeErrors, MeResponses, StartRetrievalData, StartRetrievalErrors, StartRetrievalResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Engagements Route
 */
export const listEngagements = <ThrowOnError extends boolean = false>(options?: Options<ListEngagementsData, ThrowOnError>): RequestResult<ListEngagementsResponses, ListEngagementsErrors, ThrowOnError> => (options?.client ?? client).get<ListEngagementsResponses, ListEngagementsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/engagements',
    ...options
});

/**
 * Create Engagement Route
 */
export const createEngagement = <ThrowOnError extends boolean = false>(options: Options<CreateEngagementData, ThrowOnError>): RequestResult<CreateEngagementResponses, CreateEngagementErrors, ThrowOnError> => (options.client ?? client).post<CreateEngagementResponses, CreateEngagementErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/engagements',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Engagement Route
 */
export const getEngagement = <ThrowOnError extends boolean = false>(options: Options<GetEngagementData, ThrowOnError>): RequestResult<GetEngagementResponses, GetEngagementErrors, ThrowOnError> => (options.client ?? client).get<GetEngagementResponses, GetEngagementErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/engagements/{engagement_id}',
    ...options
});

/**
 * List Request Items Route
 */
export const listRequestItems = <ThrowOnError extends boolean = false>(options: Options<ListRequestItemsData, ThrowOnError>): RequestResult<ListRequestItemsResponses, ListRequestItemsErrors, ThrowOnError> => (options.client ?? client).get<ListRequestItemsResponses, ListRequestItemsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/engagements/{engagement_id}/request-items',
    ...options
});

/**
 * Create Request Item Route
 */
export const createRequestItem = <ThrowOnError extends boolean = false>(options: Options<CreateRequestItemData, ThrowOnError>): RequestResult<CreateRequestItemResponses, CreateRequestItemErrors, ThrowOnError> => (options.client ?? client).post<CreateRequestItemResponses, CreateRequestItemErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/engagements/{engagement_id}/request-items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start Retrieval Route
 */
export const startRetrieval = <ThrowOnError extends boolean = false>(options: Options<StartRetrievalData, ThrowOnError>): RequestResult<StartRetrievalResponses, StartRetrievalErrors, ThrowOnError> => (options.client ?? client).post<StartRetrievalResponses, StartRetrievalErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/engagements/{engagement_id}/retrievals',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Retrieval Route
 */
export const getRetrieval = <ThrowOnError extends boolean = false>(options: Options<GetRetrievalData, ThrowOnError>): RequestResult<GetRetrievalResponses, GetRetrievalErrors, ThrowOnError> => (options.client ?? client).get<GetRetrievalResponses, GetRetrievalErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/engagements/{engagement_id}/retrievals/{sync_run_id}',
    ...options
});

/**
 * Me
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, MeErrors, ThrowOnError> => (options?.client ?? client).get<MeResponses, MeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me',
    ...options
});
