// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * EngagementIn
 */
export type EngagementIn = {
    /**
     * Client Entity Name
     */
    client_entity_name: string;
    /**
     * Client Name
     */
    client_name: string;
    /**
     * Fiscal Period End
     */
    fiscal_period_end: string;
    /**
     * Fiscal Period Start
     */
    fiscal_period_start: string;
    /**
     * Name
     */
    name: string;
};

/**
 * EngagementOut
 */
export type EngagementOut = {
    /**
     * Client Entity Name
     */
    client_entity_name: string;
    /**
     * Client Name
     */
    client_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Fiscal Period End
     */
    fiscal_period_end: string;
    /**
     * Fiscal Period Start
     */
    fiscal_period_start: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'active' | 'archived';
    /**
     * Team
     */
    team: Array<TeamMemberOut>;
    /**
     * Type
     */
    type: 'audit';
};

/**
 * EngagementSummaryOut
 */
export type EngagementSummaryOut = {
    /**
     * Client Entity Name
     */
    client_entity_name: string;
    /**
     * Client Name
     */
    client_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Fiscal Period End
     */
    fiscal_period_end: string;
    /**
     * Fiscal Period Start
     */
    fiscal_period_start: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'active' | 'archived';
    /**
     * Type
     */
    type: 'audit';
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MeOut
 */
export type MeOut = {
    /**
     * Active Tenant Id
     */
    active_tenant_id: string | null;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Memberships
     */
    memberships: Array<MembershipOut>;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * MembershipOut
 */
export type MembershipOut = {
    /**
     * Firm Name
     */
    firm_name: string;
    /**
     * Firm Role
     */
    firm_role: 'firm_admin' | 'practice_leader' | 'quality_partner' | null;
    /**
     * Tenant Id
     */
    tenant_id: string;
};

/**
 * RequestItemIn
 */
export type RequestItemIn = {
    /**
     * Audit Area
     */
    audit_area: string;
    /**
     * Description
     */
    description: string;
};

/**
 * RequestItemOut
 */
export type RequestItemOut = {
    /**
     * Audit Area
     */
    audit_area: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Description
     */
    description: string;
    /**
     * Engagement Id
     */
    engagement_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'open' | 'received' | 'ready_for_review' | 'needs_revision';
};

/**
 * TeamMemberOut
 */
export type TeamMemberOut = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Role
     */
    role: 'engagement_partner' | 'manager' | 'senior' | 'staff' | 'reviewer';
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListEngagementsData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/engagements';
};

export type ListEngagementsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEngagementsError = ListEngagementsErrors[keyof ListEngagementsErrors];

export type ListEngagementsResponses = {
    /**
     * Response List Engagements
     *
     * Successful Response
     */
    200: Array<EngagementSummaryOut>;
};

export type ListEngagementsResponse = ListEngagementsResponses[keyof ListEngagementsResponses];

export type CreateEngagementData = {
    body: EngagementIn;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/engagements';
};

export type CreateEngagementErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEngagementError = CreateEngagementErrors[keyof CreateEngagementErrors];

export type CreateEngagementResponses = {
    /**
     * Successful Response
     */
    201: EngagementOut;
};

export type CreateEngagementResponse = CreateEngagementResponses[keyof CreateEngagementResponses];

export type GetEngagementData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}';
};

export type GetEngagementErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEngagementError = GetEngagementErrors[keyof GetEngagementErrors];

export type GetEngagementResponses = {
    /**
     * Successful Response
     */
    200: EngagementOut;
};

export type GetEngagementResponse = GetEngagementResponses[keyof GetEngagementResponses];

export type ListRequestItemsData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}/request-items';
};

export type ListRequestItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRequestItemsError = ListRequestItemsErrors[keyof ListRequestItemsErrors];

export type ListRequestItemsResponses = {
    /**
     * Response List Request Items
     *
     * Successful Response
     */
    200: Array<RequestItemOut>;
};

export type ListRequestItemsResponse = ListRequestItemsResponses[keyof ListRequestItemsResponses];

export type CreateRequestItemData = {
    body: RequestItemIn;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}/request-items';
};

export type CreateRequestItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRequestItemError = CreateRequestItemErrors[keyof CreateRequestItemErrors];

export type CreateRequestItemResponses = {
    /**
     * Successful Response
     */
    201: RequestItemOut;
};

export type CreateRequestItemResponse = CreateRequestItemResponses[keyof CreateRequestItemResponses];

export type MeData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type MeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Successful Response
     */
    200: MeOut;
};

export type MeResponse = MeResponses[keyof MeResponses];
