// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CitationOut
 */
export type CitationOut = {
    /**
     * Cell
     */
    cell: string;
    /**
     * Quote
     */
    quote: string | null;
    /**
     * Reason
     */
    reason: 'cell_not_found' | 'quote_mismatch' | 'value_mismatch' | null;
    /**
     * Value
     */
    value: string | null;
    /**
     * Verified
     */
    verified: boolean;
};

/**
 * EngagementIn
 */
export type EngagementIn = {
    /**
     * Client Entity Name
     */
    client_entity_name: string;
    /**
     * Client Name
     */
    client_name: string;
    /**
     * Fiscal Period End
     */
    fiscal_period_end: string;
    /**
     * Fiscal Period Start
     */
    fiscal_period_start: string;
    /**
     * Name
     */
    name: string;
};

/**
 * EngagementOut
 */
export type EngagementOut = {
    /**
     * Client Entity Name
     */
    client_entity_name: string;
    /**
     * Client Name
     */
    client_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Fiscal Period End
     */
    fiscal_period_end: string;
    /**
     * Fiscal Period Start
     */
    fiscal_period_start: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'active' | 'archived';
    /**
     * Team
     */
    team: Array<TeamMemberOut>;
    /**
     * Type
     */
    type: 'audit';
};

/**
 * EngagementSummaryOut
 */
export type EngagementSummaryOut = {
    /**
     * Client Entity Name
     */
    client_entity_name: string;
    /**
     * Client Name
     */
    client_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Fiscal Period End
     */
    fiscal_period_end: string;
    /**
     * Fiscal Period Start
     */
    fiscal_period_start: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'active' | 'archived';
    /**
     * Type
     */
    type: 'audit';
};

/**
 * ErrorOut
 */
export type ErrorOut = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * EvidenceVersionOut
 */
export type EvidenceVersionOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Evidence Item Id
     */
    evidence_item_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Method
     */
    method: 'retrieved' | 'uploaded';
    /**
     * Period End
     */
    period_end: string | null;
    /**
     * Period Start
     */
    period_start: string | null;
    /**
     * Pulled At
     */
    pulled_at: string | null;
    /**
     * Source
     */
    source: string;
    /**
     * Version No
     */
    version_no: number;
};

/**
 * FieldErrorOut
 */
export type FieldErrorOut = {
    /**
     * Loc
     */
    loc: Array<string | number>;
    /**
     * Msg
     */
    msg: string;
    /**
     * Type
     */
    type: string;
};

/**
 * MeOut
 */
export type MeOut = {
    /**
     * Active Tenant Id
     */
    active_tenant_id: string | null;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Memberships
     */
    memberships: Array<MembershipOut>;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * MembershipOut
 */
export type MembershipOut = {
    /**
     * Firm Name
     */
    firm_name: string;
    /**
     * Firm Role
     */
    firm_role: 'firm_admin' | 'practice_leader' | 'quality_partner' | null;
    /**
     * Tenant Id
     */
    tenant_id: string;
};

/**
 * RequestItemIn
 */
export type RequestItemIn = {
    /**
     * Audit Area
     */
    audit_area: string;
    /**
     * Description
     */
    description: string;
};

/**
 * RequestItemOut
 */
export type RequestItemOut = {
    /**
     * Audit Area
     */
    audit_area: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Description
     */
    description: string;
    /**
     * Engagement Id
     */
    engagement_id: string;
    /**
     * Evidence Version Id
     */
    evidence_version_id?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'open' | 'received' | 'ready_for_review' | 'needs_revision';
};

/**
 * RetrievalIn
 */
export type RetrievalIn = {
    /**
     * Period End
     */
    period_end: string;
    /**
     * Period Start
     */
    period_start: string;
    /**
     * Request Item Id
     */
    request_item_id: string;
};

/**
 * RetrievalOut
 */
export type RetrievalOut = {
    /**
     * Evidence Version Id
     */
    evidence_version_id: string | null;
    /**
     * Failure Code
     */
    failure_code: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Request Item Id
     */
    request_item_id: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Status
     */
    status: 'running' | 'succeeded' | 'failed_validation' | 'failed';
    /**
     * Sync Run Id
     */
    sync_run_id: string;
};

/**
 * ScreeningResultOut
 *
 * Model text (`rationale`, `quote`, `unverified`) is untrusted: render as plain text.
 */
export type ScreeningResultOut = {
    /**
     * Action
     */
    action: 'ready_for_review' | 'needs_revision';
    /**
     * Citations
     */
    citations: Array<CitationOut>;
    /**
     * Confidence
     */
    confidence: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Evidence Version Id
     */
    evidence_version_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Rationale
     */
    rationale: string;
    /**
     * Unverified
     */
    unverified: Array<string>;
};

/**
 * TeamMemberOut
 */
export type TeamMemberOut = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Role
     */
    role: 'engagement_partner' | 'manager' | 'senior' | 'staff' | 'reviewer';
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ValidationErrorOut
 *
 * What a 422 says: where and what, never the submitted value (abacus.api.app).
 */
export type ValidationErrorOut = {
    /**
     * Detail
     */
    detail: Array<FieldErrorOut>;
};

/**
 * WallIn
 */
export type WallIn = {
    /**
     * Client Id
     */
    client_id: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * WallOut
 *
 * Who is walled off from which client is itself sensitive (conflicts of interest).
 */
export type WallOut = {
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Id
     */
    id: string;
    /**
     * Removed At
     */
    removed_at: string | null;
    /**
     * Removed By
     */
    removed_by: string | null;
    /**
     * Status
     */
    status: 'active' | 'removed';
    /**
     * User Id
     */
    user_id: string;
};

export type ListEngagementsData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/engagements';
};

export type ListEngagementsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type ListEngagementsError = ListEngagementsErrors[keyof ListEngagementsErrors];

export type ListEngagementsResponses = {
    /**
     * Response List Engagements
     *
     * Successful Response
     */
    200: Array<EngagementSummaryOut>;
};

export type ListEngagementsResponse = ListEngagementsResponses[keyof ListEngagementsResponses];

export type CreateEngagementData = {
    body: EngagementIn;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/engagements';
};

export type CreateEngagementErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type CreateEngagementError = CreateEngagementErrors[keyof CreateEngagementErrors];

export type CreateEngagementResponses = {
    /**
     * Successful Response
     */
    201: EngagementOut;
};

export type CreateEngagementResponse = CreateEngagementResponses[keyof CreateEngagementResponses];

export type GetEngagementData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}';
};

export type GetEngagementErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type GetEngagementError = GetEngagementErrors[keyof GetEngagementErrors];

export type GetEngagementResponses = {
    /**
     * Successful Response
     */
    200: EngagementOut;
};

export type GetEngagementResponse = GetEngagementResponses[keyof GetEngagementResponses];

export type ListEvidenceVersionsData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}/evidence-versions';
};

export type ListEvidenceVersionsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type ListEvidenceVersionsError = ListEvidenceVersionsErrors[keyof ListEvidenceVersionsErrors];

export type ListEvidenceVersionsResponses = {
    /**
     * Response List Evidence Versions
     *
     * Successful Response
     */
    200: Array<EvidenceVersionOut>;
};

export type ListEvidenceVersionsResponse = ListEvidenceVersionsResponses[keyof ListEvidenceVersionsResponses];

export type ListRequestItemsData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}/request-items';
};

export type ListRequestItemsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type ListRequestItemsError = ListRequestItemsErrors[keyof ListRequestItemsErrors];

export type ListRequestItemsResponses = {
    /**
     * Response List Request Items
     *
     * Successful Response
     */
    200: Array<RequestItemOut>;
};

export type ListRequestItemsResponse = ListRequestItemsResponses[keyof ListRequestItemsResponses];

export type CreateRequestItemData = {
    body: RequestItemIn;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}/request-items';
};

export type CreateRequestItemErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type CreateRequestItemError = CreateRequestItemErrors[keyof CreateRequestItemErrors];

export type CreateRequestItemResponses = {
    /**
     * Successful Response
     */
    201: RequestItemOut;
};

export type CreateRequestItemResponse = CreateRequestItemResponses[keyof CreateRequestItemResponses];

export type StartRetrievalData = {
    body: RetrievalIn;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}/retrievals';
};

export type StartRetrievalErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict with the resource's state
     */
    409: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
    /**
     * Service unavailable
     */
    503: ErrorOut;
};

export type StartRetrievalError = StartRetrievalErrors[keyof StartRetrievalErrors];

export type StartRetrievalResponses = {
    /**
     * Successful Response
     */
    202: RetrievalOut;
};

export type StartRetrievalResponse = StartRetrievalResponses[keyof StartRetrievalResponses];

export type GetRetrievalData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
        /**
         * Sync Run Id
         */
        sync_run_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}/retrievals/{sync_run_id}';
};

export type GetRetrievalErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type GetRetrievalError = GetRetrievalErrors[keyof GetRetrievalErrors];

export type GetRetrievalResponses = {
    /**
     * Successful Response
     */
    200: RetrievalOut;
};

export type GetRetrievalResponse = GetRetrievalResponses[keyof GetRetrievalResponses];

export type ListScreeningResultsData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Engagement Id
         */
        engagement_id: string;
    };
    query?: never;
    url: '/v1/engagements/{engagement_id}/screening-results';
};

export type ListScreeningResultsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type ListScreeningResultsError = ListScreeningResultsErrors[keyof ListScreeningResultsErrors];

export type ListScreeningResultsResponses = {
    /**
     * Response List Screening Results
     *
     * Successful Response
     */
    200: Array<ScreeningResultOut>;
};

export type ListScreeningResultsResponse = ListScreeningResultsResponses[keyof ListScreeningResultsResponses];

export type MeData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type MeErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Successful Response
     */
    200: MeOut;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListWallsData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/walls';
};

export type ListWallsErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type ListWallsError = ListWallsErrors[keyof ListWallsErrors];

export type ListWallsResponses = {
    /**
     * Response List Walls
     *
     * Successful Response
     */
    200: Array<WallOut>;
};

export type ListWallsResponse = ListWallsResponses[keyof ListWallsResponses];

export type CreateWallData = {
    body: WallIn;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/walls';
};

export type CreateWallErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type CreateWallError = CreateWallErrors[keyof CreateWallErrors];

export type CreateWallResponses = {
    /**
     * Successful Response
     */
    201: WallOut;
};

export type CreateWallResponse = CreateWallResponses[keyof CreateWallResponses];

export type RemoveWallData = {
    body?: never;
    headers?: {
        /**
         * X-Abacus-Tenant
         */
        'X-Abacus-Tenant'?: string | null;
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Wall Id
         */
        wall_id: string;
    };
    query?: never;
    url: '/v1/walls/{wall_id}/remove';
};

export type RemoveWallErrors = {
    /**
     * Not authenticated
     */
    401: ErrorOut;
    /**
     * Forbidden
     */
    403: ErrorOut;
    /**
     * Not found
     */
    404: ErrorOut;
    /**
     * Conflict with the resource's state
     */
    409: ErrorOut;
    /**
     * Invalid request
     */
    422: ValidationErrorOut;
};

export type RemoveWallError = RemoveWallErrors[keyof RemoveWallErrors];

export type RemoveWallResponses = {
    /**
     * Successful Response
     */
    200: WallOut;
};

export type RemoveWallResponse = RemoveWallResponses[keyof RemoveWallResponses];
