// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { accept, addDocument, applyMethodology, assign, createEngagement, createRequestItem, createWall, engagementGraph, getBudget, getDocument, getEngagement, getRetrieval, getVersion, importTemplate, listDocuments, listEngagements, listEvidenceVersions, listRequestItems, listScreeningResults, listTemplates, listWalls, me, metering, type Options, putBudget, reasonCodes, reject, release, removeWall, reviewQueue, search, sendBack, startRetrieval, take, withdrawDocument } from '../sdk.gen';
import type { AcceptData, AcceptError, AcceptResponse, AddDocumentData, AddDocumentError, AddDocumentResponse, ApplyMethodologyData, ApplyMethodologyError, ApplyMethodologyResponse, AssignData, AssignError, AssignResponse, CreateEngagementData, CreateEngagementError, CreateEngagementResponse, CreateRequestItemData, CreateRequestItemError, CreateRequestItemResponse, CreateWallData, CreateWallError, CreateWallResponse, EngagementGraphData, EngagementGraphError, EngagementGraphResponse, GetBudgetData, GetBudgetError, GetBudgetResponse, GetDocumentData, GetDocumentError, GetDocumentResponse, GetEngagementData, GetEngagementError, GetEngagementResponse, GetRetrievalData, GetRetrievalError, GetRetrievalResponse, GetVersionData, GetVersionError, GetVersionResponse, ImportTemplateData, ImportTemplateError, ImportTemplateResponse, ListDocumentsData, ListDocumentsError, ListDocumentsResponse, ListEngagementsData, ListEngagementsError, ListEngagementsResponse, ListEvidenceVersionsData, ListEvidenceVersionsError, ListEvidenceVersionsResponse, ListRequestItemsData, ListRequestItemsError, ListRequestItemsResponse, ListScreeningResultsData, ListScreeningResultsError, ListScreeningResultsResponse, ListTemplatesData, ListTemplatesError, ListTemplatesResponse, ListWallsData, ListWallsError, ListWallsResponse, MeData, MeError, MeResponse, MeteringData, MeteringError, MeteringResponse, PutBudgetData, PutBudgetError, PutBudgetResponse, ReasonCodesData, ReasonCodesError, ReasonCodesResponse, RejectData, RejectError, RejectResponse, ReleaseData, ReleaseError, ReleaseResponse, RemoveWallData, RemoveWallError, RemoveWallResponse, ReviewQueueData, ReviewQueueError, ReviewQueueResponse, SearchData, SearchError, SearchResponse, SendBackData, SendBackError, SendBackResponse, StartRetrievalData, StartRetrievalError, StartRetrievalResponse, TakeData, TakeError, TakeResponse, WithdrawDocumentData, WithdrawDocumentError, WithdrawDocumentResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getBudgetQueryKey = (options?: Options<GetBudgetData>) => createQueryKey('getBudget', options);

/**
 * Get Budget Route
 */
export const getBudgetOptions = (options?: Options<GetBudgetData>) => queryOptions<GetBudgetResponse, GetBudgetError, GetBudgetResponse, ReturnType<typeof getBudgetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBudget({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBudgetQueryKey(options)
});

/**
 * Put Budget Route
 */
export const putBudgetMutation = (options?: Partial<Options<PutBudgetData>>): UseMutationOptions<PutBudgetResponse, PutBudgetError, Options<PutBudgetData>> => {
    const mutationOptions: UseMutationOptions<PutBudgetResponse, PutBudgetError, Options<PutBudgetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putBudget({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listEngagementsQueryKey = (options?: Options<ListEngagementsData>) => createQueryKey('listEngagements', options);

/**
 * List Engagements Route
 */
export const listEngagementsOptions = (options?: Options<ListEngagementsData>) => queryOptions<ListEngagementsResponse, ListEngagementsError, ListEngagementsResponse, ReturnType<typeof listEngagementsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEngagements({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEngagementsQueryKey(options)
});

/**
 * Create Engagement Route
 */
export const createEngagementMutation = (options?: Partial<Options<CreateEngagementData>>): UseMutationOptions<CreateEngagementResponse, CreateEngagementError, Options<CreateEngagementData>> => {
    const mutationOptions: UseMutationOptions<CreateEngagementResponse, CreateEngagementError, Options<CreateEngagementData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEngagement({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEngagementQueryKey = (options: Options<GetEngagementData>) => createQueryKey('getEngagement', options);

/**
 * Get Engagement Route
 */
export const getEngagementOptions = (options: Options<GetEngagementData>) => queryOptions<GetEngagementResponse, GetEngagementError, GetEngagementResponse, ReturnType<typeof getEngagementQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEngagement({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEngagementQueryKey(options)
});

export const listEvidenceVersionsQueryKey = (options: Options<ListEvidenceVersionsData>) => createQueryKey('listEvidenceVersions', options);

/**
 * List Evidence Versions Route
 */
export const listEvidenceVersionsOptions = (options: Options<ListEvidenceVersionsData>) => queryOptions<ListEvidenceVersionsResponse, ListEvidenceVersionsError, ListEvidenceVersionsResponse, ReturnType<typeof listEvidenceVersionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEvidenceVersions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEvidenceVersionsQueryKey(options)
});

/**
 * Accept Route
 */
export const acceptMutation = (options?: Partial<Options<AcceptData>>): UseMutationOptions<AcceptResponse, AcceptError, Options<AcceptData>> => {
    const mutationOptions: UseMutationOptions<AcceptResponse, AcceptError, Options<AcceptData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await accept({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reject Route
 */
export const rejectMutation = (options?: Partial<Options<RejectData>>): UseMutationOptions<RejectResponse, RejectError, Options<RejectData>> => {
    const mutationOptions: UseMutationOptions<RejectResponse, RejectError, Options<RejectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Send Back Route
 */
export const sendBackMutation = (options?: Partial<Options<SendBackData>>): UseMutationOptions<SendBackResponse, SendBackError, Options<SendBackData>> => {
    const mutationOptions: UseMutationOptions<SendBackResponse, SendBackError, Options<SendBackData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendBack({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const engagementGraphQueryKey = (options: Options<EngagementGraphData>) => createQueryKey('engagementGraph', options);

/**
 * Engagement Graph Route
 */
export const engagementGraphOptions = (options: Options<EngagementGraphData>) => queryOptions<EngagementGraphResponse, EngagementGraphError, EngagementGraphResponse, ReturnType<typeof engagementGraphQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await engagementGraph({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: engagementGraphQueryKey(options)
});

/**
 * Apply Methodology Route
 */
export const applyMethodologyMutation = (options?: Partial<Options<ApplyMethodologyData>>): UseMutationOptions<ApplyMethodologyResponse, ApplyMethodologyError, Options<ApplyMethodologyData>> => {
    const mutationOptions: UseMutationOptions<ApplyMethodologyResponse, ApplyMethodologyError, Options<ApplyMethodologyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await applyMethodology({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRequestItemsQueryKey = (options: Options<ListRequestItemsData>) => createQueryKey('listRequestItems', options);

/**
 * List Request Items Route
 */
export const listRequestItemsOptions = (options: Options<ListRequestItemsData>) => queryOptions<ListRequestItemsResponse, ListRequestItemsError, ListRequestItemsResponse, ReturnType<typeof listRequestItemsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRequestItems({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRequestItemsQueryKey(options)
});

/**
 * Create Request Item Route
 */
export const createRequestItemMutation = (options?: Partial<Options<CreateRequestItemData>>): UseMutationOptions<CreateRequestItemResponse, CreateRequestItemError, Options<CreateRequestItemData>> => {
    const mutationOptions: UseMutationOptions<CreateRequestItemResponse, CreateRequestItemError, Options<CreateRequestItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRequestItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start Retrieval Route
 */
export const startRetrievalMutation = (options?: Partial<Options<StartRetrievalData>>): UseMutationOptions<StartRetrievalResponse, StartRetrievalError, Options<StartRetrievalData>> => {
    const mutationOptions: UseMutationOptions<StartRetrievalResponse, StartRetrievalError, Options<StartRetrievalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startRetrieval({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRetrievalQueryKey = (options: Options<GetRetrievalData>) => createQueryKey('getRetrieval', options);

/**
 * Get Retrieval Route
 */
export const getRetrievalOptions = (options: Options<GetRetrievalData>) => queryOptions<GetRetrievalResponse, GetRetrievalError, GetRetrievalResponse, ReturnType<typeof getRetrievalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRetrieval({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRetrievalQueryKey(options)
});

export const reviewQueueQueryKey = (options: Options<ReviewQueueData>) => createQueryKey('reviewQueue', options);

/**
 * Review Queue Route
 */
export const reviewQueueOptions = (options: Options<ReviewQueueData>) => queryOptions<ReviewQueueResponse, ReviewQueueError, ReviewQueueResponse, ReturnType<typeof reviewQueueQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await reviewQueue({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: reviewQueueQueryKey(options)
});

/**
 * Assign Route
 */
export const assignMutation = (options?: Partial<Options<AssignData>>): UseMutationOptions<AssignResponse, AssignError, Options<AssignData>> => {
    const mutationOptions: UseMutationOptions<AssignResponse, AssignError, Options<AssignData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assign({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Release Route
 */
export const releaseMutation = (options?: Partial<Options<ReleaseData>>): UseMutationOptions<ReleaseResponse, ReleaseError, Options<ReleaseData>> => {
    const mutationOptions: UseMutationOptions<ReleaseResponse, ReleaseError, Options<ReleaseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await release({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Take Route
 */
export const takeMutation = (options?: Partial<Options<TakeData>>): UseMutationOptions<TakeResponse, TakeError, Options<TakeData>> => {
    const mutationOptions: UseMutationOptions<TakeResponse, TakeError, Options<TakeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await take({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const reasonCodesQueryKey = (options: Options<ReasonCodesData>) => createQueryKey('reasonCodes', options);

/**
 * Reason Codes Route
 */
export const reasonCodesOptions = (options: Options<ReasonCodesData>) => queryOptions<ReasonCodesResponse, ReasonCodesError, ReasonCodesResponse, ReturnType<typeof reasonCodesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await reasonCodes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: reasonCodesQueryKey(options)
});

export const listScreeningResultsQueryKey = (options: Options<ListScreeningResultsData>) => createQueryKey('listScreeningResults', options);

/**
 * List Screening Results Route
 */
export const listScreeningResultsOptions = (options: Options<ListScreeningResultsData>) => queryOptions<ListScreeningResultsResponse, ListScreeningResultsError, ListScreeningResultsResponse, ReturnType<typeof listScreeningResultsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listScreeningResults({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listScreeningResultsQueryKey(options)
});

export const listDocumentsQueryKey = (options?: Options<ListDocumentsData>) => createQueryKey('listDocuments', options);

/**
 * List Documents Route
 */
export const listDocumentsOptions = (options?: Options<ListDocumentsData>) => queryOptions<ListDocumentsResponse, ListDocumentsError, ListDocumentsResponse, ReturnType<typeof listDocumentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listDocuments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listDocumentsQueryKey(options)
});

/**
 * Add Document Route
 */
export const addDocumentMutation = (options?: Partial<Options<AddDocumentData>>): UseMutationOptions<AddDocumentResponse, AddDocumentError, Options<AddDocumentData>> => {
    const mutationOptions: UseMutationOptions<AddDocumentResponse, AddDocumentError, Options<AddDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDocumentQueryKey = (options: Options<GetDocumentData>) => createQueryKey('getDocument', options);

/**
 * Get Document Route
 */
export const getDocumentOptions = (options: Options<GetDocumentData>) => queryOptions<GetDocumentResponse, GetDocumentError, GetDocumentResponse, ReturnType<typeof getDocumentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDocument({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDocumentQueryKey(options)
});

/**
 * Withdraw Document Route
 */
export const withdrawDocumentMutation = (options?: Partial<Options<WithdrawDocumentData>>): UseMutationOptions<WithdrawDocumentResponse, WithdrawDocumentError, Options<WithdrawDocumentData>> => {
    const mutationOptions: UseMutationOptions<WithdrawDocumentResponse, WithdrawDocumentError, Options<WithdrawDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await withdrawDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Search Route
 */
export const searchMutation = (options?: Partial<Options<SearchData>>): UseMutationOptions<SearchResponse, SearchError, Options<SearchData>> => {
    const mutationOptions: UseMutationOptions<SearchResponse, SearchError, Options<SearchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await search({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

/**
 * Me
 */
export const meOptions = (options?: Options<MeData>) => queryOptions<MeResponse, MeError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await me({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meQueryKey(options)
});

export const meteringQueryKey = (options?: Options<MeteringData>) => createQueryKey('metering', options);

/**
 * Metering Route
 */
export const meteringOptions = (options?: Options<MeteringData>) => queryOptions<MeteringResponse, MeteringError, MeteringResponse, ReturnType<typeof meteringQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await metering({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meteringQueryKey(options)
});

export const listTemplatesQueryKey = (options?: Options<ListTemplatesData>) => createQueryKey('listTemplates', options);

/**
 * List Templates Route
 */
export const listTemplatesOptions = (options?: Options<ListTemplatesData>) => queryOptions<ListTemplatesResponse, ListTemplatesError, ListTemplatesResponse, ReturnType<typeof listTemplatesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTemplates({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTemplatesQueryKey(options)
});

/**
 * Import Template Route
 *
 * The raw `.xlsx` workbook is the request body (TASK-023 D3: no multipart dependency).
 */
export const importTemplateMutation = (options?: Partial<Options<ImportTemplateData>>): UseMutationOptions<ImportTemplateResponse, ImportTemplateError, Options<ImportTemplateData>> => {
    const mutationOptions: UseMutationOptions<ImportTemplateResponse, ImportTemplateError, Options<ImportTemplateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await importTemplate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getVersionQueryKey = (options: Options<GetVersionData>) => createQueryKey('getVersion', options);

/**
 * Get Version Route
 */
export const getVersionOptions = (options: Options<GetVersionData>) => queryOptions<GetVersionResponse, GetVersionError, GetVersionResponse, ReturnType<typeof getVersionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getVersion({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getVersionQueryKey(options)
});

export const listWallsQueryKey = (options?: Options<ListWallsData>) => createQueryKey('listWalls', options);

/**
 * List Walls Route
 */
export const listWallsOptions = (options?: Options<ListWallsData>) => queryOptions<ListWallsResponse, ListWallsError, ListWallsResponse, ReturnType<typeof listWallsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listWalls({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listWallsQueryKey(options)
});

/**
 * Create Wall Route
 */
export const createWallMutation = (options?: Partial<Options<CreateWallData>>): UseMutationOptions<CreateWallResponse, CreateWallError, Options<CreateWallData>> => {
    const mutationOptions: UseMutationOptions<CreateWallResponse, CreateWallError, Options<CreateWallData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createWall({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove Wall Route
 *
 * Walls are never deleted: removing one returns it, marked removed.
 */
export const removeWallMutation = (options?: Partial<Options<RemoveWallData>>): UseMutationOptions<RemoveWallResponse, RemoveWallError, Options<RemoveWallData>> => {
    const mutationOptions: UseMutationOptions<RemoveWallResponse, RemoveWallError, Options<RemoveWallData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeWall({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
