// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { accept, assign, createEngagement, createRequestItem, createWall, getEngagement, getRetrieval, listEngagements, listEvidenceVersions, listRequestItems, listScreeningResults, listWalls, me, type Options, reasonCodes, reject, release, removeWall, reviewQueue, sendBack, startRetrieval, take } from '../sdk.gen';
import type { AcceptData, AcceptError, AcceptResponse, AssignData, AssignError, AssignResponse, CreateEngagementData, CreateEngagementError, CreateEngagementResponse, CreateRequestItemData, CreateRequestItemError, CreateRequestItemResponse, CreateWallData, CreateWallError, CreateWallResponse, GetEngagementData, GetEngagementError, GetEngagementResponse, GetRetrievalData, GetRetrievalError, GetRetrievalResponse, ListEngagementsData, ListEngagementsError, ListEngagementsResponse, ListEvidenceVersionsData, ListEvidenceVersionsError, ListEvidenceVersionsResponse, ListRequestItemsData, ListRequestItemsError, ListRequestItemsResponse, ListScreeningResultsData, ListScreeningResultsError, ListScreeningResultsResponse, ListWallsData, ListWallsError, ListWallsResponse, MeData, MeError, MeResponse, ReasonCodesData, ReasonCodesError, ReasonCodesResponse, RejectData, RejectError, RejectResponse, ReleaseData, ReleaseError, ReleaseResponse, RemoveWallData, RemoveWallError, RemoveWallResponse, ReviewQueueData, ReviewQueueError, ReviewQueueResponse, SendBackData, SendBackError, SendBackResponse, StartRetrievalData, StartRetrievalError, StartRetrievalResponse, TakeData, TakeError, TakeResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listEngagementsQueryKey = (options?: Options<ListEngagementsData>) => createQueryKey('listEngagements', options);

/**
 * List Engagements Route
 */
export const listEngagementsOptions = (options?: Options<ListEngagementsData>) => queryOptions<ListEngagementsResponse, ListEngagementsError, ListEngagementsResponse, ReturnType<typeof listEngagementsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEngagements({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEngagementsQueryKey(options)
});

/**
 * Create Engagement Route
 */
export const createEngagementMutation = (options?: Partial<Options<CreateEngagementData>>): UseMutationOptions<CreateEngagementResponse, CreateEngagementError, Options<CreateEngagementData>> => {
    const mutationOptions: UseMutationOptions<CreateEngagementResponse, CreateEngagementError, Options<CreateEngagementData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEngagement({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEngagementQueryKey = (options: Options<GetEngagementData>) => createQueryKey('getEngagement', options);

/**
 * Get Engagement Route
 */
export const getEngagementOptions = (options: Options<GetEngagementData>) => queryOptions<GetEngagementResponse, GetEngagementError, GetEngagementResponse, ReturnType<typeof getEngagementQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEngagement({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEngagementQueryKey(options)
});

export const listEvidenceVersionsQueryKey = (options: Options<ListEvidenceVersionsData>) => createQueryKey('listEvidenceVersions', options);

/**
 * List Evidence Versions Route
 */
export const listEvidenceVersionsOptions = (options: Options<ListEvidenceVersionsData>) => queryOptions<ListEvidenceVersionsResponse, ListEvidenceVersionsError, ListEvidenceVersionsResponse, ReturnType<typeof listEvidenceVersionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEvidenceVersions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEvidenceVersionsQueryKey(options)
});

/**
 * Accept Route
 */
export const acceptMutation = (options?: Partial<Options<AcceptData>>): UseMutationOptions<AcceptResponse, AcceptError, Options<AcceptData>> => {
    const mutationOptions: UseMutationOptions<AcceptResponse, AcceptError, Options<AcceptData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await accept({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reject Route
 */
export const rejectMutation = (options?: Partial<Options<RejectData>>): UseMutationOptions<RejectResponse, RejectError, Options<RejectData>> => {
    const mutationOptions: UseMutationOptions<RejectResponse, RejectError, Options<RejectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Send Back Route
 */
export const sendBackMutation = (options?: Partial<Options<SendBackData>>): UseMutationOptions<SendBackResponse, SendBackError, Options<SendBackData>> => {
    const mutationOptions: UseMutationOptions<SendBackResponse, SendBackError, Options<SendBackData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendBack({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRequestItemsQueryKey = (options: Options<ListRequestItemsData>) => createQueryKey('listRequestItems', options);

/**
 * List Request Items Route
 */
export const listRequestItemsOptions = (options: Options<ListRequestItemsData>) => queryOptions<ListRequestItemsResponse, ListRequestItemsError, ListRequestItemsResponse, ReturnType<typeof listRequestItemsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRequestItems({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRequestItemsQueryKey(options)
});

/**
 * Create Request Item Route
 */
export const createRequestItemMutation = (options?: Partial<Options<CreateRequestItemData>>): UseMutationOptions<CreateRequestItemResponse, CreateRequestItemError, Options<CreateRequestItemData>> => {
    const mutationOptions: UseMutationOptions<CreateRequestItemResponse, CreateRequestItemError, Options<CreateRequestItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRequestItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start Retrieval Route
 */
export const startRetrievalMutation = (options?: Partial<Options<StartRetrievalData>>): UseMutationOptions<StartRetrievalResponse, StartRetrievalError, Options<StartRetrievalData>> => {
    const mutationOptions: UseMutationOptions<StartRetrievalResponse, StartRetrievalError, Options<StartRetrievalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startRetrieval({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRetrievalQueryKey = (options: Options<GetRetrievalData>) => createQueryKey('getRetrieval', options);

/**
 * Get Retrieval Route
 */
export const getRetrievalOptions = (options: Options<GetRetrievalData>) => queryOptions<GetRetrievalResponse, GetRetrievalError, GetRetrievalResponse, ReturnType<typeof getRetrievalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRetrieval({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRetrievalQueryKey(options)
});

export const reviewQueueQueryKey = (options: Options<ReviewQueueData>) => createQueryKey('reviewQueue', options);

/**
 * Review Queue Route
 */
export const reviewQueueOptions = (options: Options<ReviewQueueData>) => queryOptions<ReviewQueueResponse, ReviewQueueError, ReviewQueueResponse, ReturnType<typeof reviewQueueQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await reviewQueue({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: reviewQueueQueryKey(options)
});

/**
 * Assign Route
 */
export const assignMutation = (options?: Partial<Options<AssignData>>): UseMutationOptions<AssignResponse, AssignError, Options<AssignData>> => {
    const mutationOptions: UseMutationOptions<AssignResponse, AssignError, Options<AssignData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assign({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Release Route
 */
export const releaseMutation = (options?: Partial<Options<ReleaseData>>): UseMutationOptions<ReleaseResponse, ReleaseError, Options<ReleaseData>> => {
    const mutationOptions: UseMutationOptions<ReleaseResponse, ReleaseError, Options<ReleaseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await release({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Take Route
 */
export const takeMutation = (options?: Partial<Options<TakeData>>): UseMutationOptions<TakeResponse, TakeError, Options<TakeData>> => {
    const mutationOptions: UseMutationOptions<TakeResponse, TakeError, Options<TakeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await take({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const reasonCodesQueryKey = (options: Options<ReasonCodesData>) => createQueryKey('reasonCodes', options);

/**
 * Reason Codes Route
 */
export const reasonCodesOptions = (options: Options<ReasonCodesData>) => queryOptions<ReasonCodesResponse, ReasonCodesError, ReasonCodesResponse, ReturnType<typeof reasonCodesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await reasonCodes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: reasonCodesQueryKey(options)
});

export const listScreeningResultsQueryKey = (options: Options<ListScreeningResultsData>) => createQueryKey('listScreeningResults', options);

/**
 * List Screening Results Route
 */
export const listScreeningResultsOptions = (options: Options<ListScreeningResultsData>) => queryOptions<ListScreeningResultsResponse, ListScreeningResultsError, ListScreeningResultsResponse, ReturnType<typeof listScreeningResultsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listScreeningResults({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listScreeningResultsQueryKey(options)
});

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

/**
 * Me
 */
export const meOptions = (options?: Options<MeData>) => queryOptions<MeResponse, MeError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await me({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meQueryKey(options)
});

export const listWallsQueryKey = (options?: Options<ListWallsData>) => createQueryKey('listWalls', options);

/**
 * List Walls Route
 */
export const listWallsOptions = (options?: Options<ListWallsData>) => queryOptions<ListWallsResponse, ListWallsError, ListWallsResponse, ReturnType<typeof listWallsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listWalls({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listWallsQueryKey(options)
});

/**
 * Create Wall Route
 */
export const createWallMutation = (options?: Partial<Options<CreateWallData>>): UseMutationOptions<CreateWallResponse, CreateWallError, Options<CreateWallData>> => {
    const mutationOptions: UseMutationOptions<CreateWallResponse, CreateWallError, Options<CreateWallData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createWall({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove Wall Route
 *
 * Walls are never deleted: removing one returns it, marked removed.
 */
export const removeWallMutation = (options?: Partial<Options<RemoveWallData>>): UseMutationOptions<RemoveWallResponse, RemoveWallError, Options<RemoveWallData>> => {
    const mutationOptions: UseMutationOptions<RemoveWallResponse, RemoveWallError, Options<RemoveWallData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeWall({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
